name: translation-search-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.18
  - pip=23.3.1
  - faiss-gpu=1.7.4
  - pip:
    - torch=1.10.1+cu111
    - torchaudio=0.10.1+cu111
    - torchvision=0.11.2+cu111
    - cudatoolkit=11.1.1
    - transformers
    - datasets
    - evaluate
    - sentence-transformers
    - nltk
    - "git+https://github.com/lucadiliello/bleurt-pytorch.git"
